data:extend({
  {
    type = "double-setting",
    name = "sh-search-radius",
    setting_type = "runtime-global",
    default_value = 256,
    minimum_value = 32,
    maximum_value = 2048,
    order = "a-a",
  },
  {
    type = "double-setting",
    name = "sh-max-pursuit-distance",
    setting_type = "runtime-global",
    default_value = 512,
    minimum_value = 64,
    maximum_value = 4096,
    order = "a-b",
  },
  {
    type = "int-setting",
    name = "sh-scan-interval",
    setting_type = "runtime-global",
    default_value = 60,
    minimum_value = 10,
    maximum_value = 600,
    order = "a-c",
  },
  {
    type = "int-setting",
    name = "sh-scan-budget",
    setting_type = "runtime-global",
    default_value = 4,
    minimum_value = 1,
    maximum_value = 32,
    order = "a-d",
  },
  {
    type = "bool-setting",
    name = "sh-return-home-after-combat",
    setting_type = "runtime-global",
    default_value = true,
    order = "b-a",
  },
  {
    type = "int-setting",
    name = "sh-post-combat-linger-ticks",
    setting_type = "runtime-global",
    default_value = 1800,
    minimum_value = 0,
    maximum_value = 36000,
    order = "b-a2",
  },
  {
    type = "int-setting",
    name = "sh-retreat-health-percent",
    setting_type = "runtime-global",
    default_value = 25,
    minimum_value = 0,
    maximum_value = 100,
    order = "b-a3",
  },
  {
    type = "bool-setting",
    name = "sh-retreat-include-shields",
    setting_type = "runtime-global",
    default_value = true,
    order = "b-a4",
  },
  {
    type = "bool-setting",
    name = "sh-restock-enabled",
    setting_type = "runtime-global",
    default_value = true,
    order = "b-b",
  },
  {
    type = "bool-setting",
    name = "sh-repair-enabled",
    setting_type = "runtime-global",
    default_value = true,
    order = "b-c",
  },
  {
    type = "int-setting",
    name = "sh-max-restock-ticks",
    setting_type = "runtime-global",
    default_value = 3600,
    minimum_value = 60,
    maximum_value = 36000,
    order = "b-d",
  },
  {
    type = "string-setting",
    name = "sh-enemy-prioritization",
    setting_type = "runtime-global",
    default_value = "nearest",
    allowed_values = { "nearest", "spawners-first", "units-first" },
    order = "c-a",
  },
  {
    type = "int-setting",
    name = "sh-max-idle-time",
    setting_type = "runtime-global",
    default_value = 600,
    minimum_value = 60,
    maximum_value = 18000,
    order = "c-b",
  },
  {
    type = "int-setting",
    name = "sh-spiders-per-think",
    setting_type = "runtime-global",
    default_value = 8,
    minimum_value = 1,
    maximum_value = 64,
    order = "c-c",
  },
  {
    type = "int-setting",
    name = "sh-enemy-cache-ttl",
    setting_type = "runtime-global",
    default_value = 18000,
    minimum_value = 600,
    maximum_value = 216000,
    order = "c-d",
  },
  {
    type = "bool-setting",
    name = "sh-debug-mode",
    setting_type = "runtime-global",
    default_value = false,
    order = "z-a",
  },
  {
    type = "double-setting",
    name = "sh-combat-range",
    setting_type = "runtime-global",
    default_value = 22,
    minimum_value = 8,
    maximum_value = 64,
    order = "d-a",
  },
  {
    type = "string-setting",
    name = "sh-combat-style",
    setting_type = "runtime-global",
    default_value = "strafe",
    allowed_values = { "hold", "strafe", "circle", "flank" },
    order = "d-b",
  },
  {
    type = "bool-setting",
    name = "sh-avoid-acid",
    setting_type = "runtime-global",
    default_value = true,
    order = "d-c",
  },
  {
    type = "int-setting",
    name = "sh-combat-move-interval",
    setting_type = "runtime-global",
    default_value = 90,
    minimum_value = 20,
    maximum_value = 600,
    order = "d-d",
  },
  {
    type = "int-setting",
    name = "sh-combat-pause-ticks",
    setting_type = "runtime-global",
    default_value = 45,
    minimum_value = 0,
    maximum_value = 300,
    order = "d-e",
  },
})
