data:extend({
  {
    type = "custom-input",
    name = "sh-toggle-autonomy",
    key_sequence = "CONTROL + SHIFT + H",
    consuming = "game-only",
    action = "lua",
  },
  {
    type = "shortcut",
    name = "sh-toggle-autonomy",
    order = "e[spidertron]-h[hunter]",
    action = "lua",
    localised_name = { "shortcut-name.sh-toggle-autonomy" },
    associated_control_input = "sh-toggle-autonomy",
    technology_to_unlock = "spidertron",
    unavailable_until_unlocked = true,
    toggleable = true,
    icon = "__SpidertronHunter__/graphics/shortcut/hunter-x56.png",
    icon_size = 56,
    small_icon = "__SpidertronHunter__/graphics/shortcut/hunter-x24.png",
    small_icon_size = 24,
  },
  {
    type = "custom-input",
    name = "sh-open-manager",
    key_sequence = "CONTROL + SHIFT + M",
    consuming = "game-only",
    action = "lua",
  },
  {
    type = "custom-input",
    name = "sh-use-alt-spidertron-remote",
    key_sequence = "CONTROL + mouse-button-2",
    controller_key_sequence = "controller-lefttrigger + controller-righttrigger + controller-a",
    consuming = "none",
    action = "lua",
    order = "a-b",
  },
  {
    type = "shortcut",
    name = "sh-open-manager",
    order = "e[spidertron]-m[manager]",
    action = "lua",
    localised_name = { "shortcut-name.sh-open-manager" },
    associated_control_input = "sh-open-manager",
    technology_to_unlock = "spidertron",
    unavailable_until_unlocked = true,
    icon = "__SpidertronHunter__/graphics/shortcut/manager-x56.png",
    icon_size = 56,
    small_icon = "__SpidertronHunter__/graphics/shortcut/manager-x24.png",
    small_icon_size = 24,
  },
})
